// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddmaglxvdgykgxtrfmsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkbWFnbHh2ZGd5a2d4dHJmbXNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMjg1MTQsImV4cCI6MjA2MTcwNDUxNH0.yb0SwJjBGjcJa4T7k21LjuDAaXQlFpzu1Kz4KKYQjRM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);